name: 'Setup Node.js'
description: 'Setup Node.js command'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '24'
  working-directory:
    description: 'Working directory'
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v6
      with:
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}package-lock.json
        node-version: ${{ inputs.node-version }}
