name: Lint

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        default: 24
      working-directory:
        type: string
        default: ./

      # markdown
      markdown-status:
        type: boolean
        default: true
      markdown-links:
        type: boolean
        default: true
      markdown-config:
        type: string
        default: .markdownlint-cli2.cjs
      markdown-input:
        type: string
        default: '**/*.md'

      # biome
      biome-status:
        type: boolean
        default: true

      # typescript
      typescript-status:
        type: boolean
        default: true

      # publint
      publint-status:
        type: boolean
        default: true
      publint-input:
        type: string
        default: './'

      # publint
      packagejson-status:
        type: boolean
        default: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint markdown
        if: ${{ inputs.markdown-status }}
        run: npx markdownlint-cli2 --config "${{ inputs.markdown-config }}" ${{ inputs.markdown-input }}

      # Disable, trigger 429 too many requests. To optimize
      #- name: Check links
      #  if: "${{ inputs.markdown-links }}"
      #  run: |
      #    find . -name '*.md' -not -path '**/node_modules/*' -exec npx markdown-link-check {} +

      - name: Biome check
        if: ${{ inputs.biome-status }}
        run: npx @biomejs/biome check .

      - name: TypeScript
        if: ${{ inputs.typescript-status }}
        run: npx --package typescript tsc --noEmit

      - name: Build (for publint)
        if: ${{ inputs.publint-status }}
        run: npm run build

      - name: Publint
        if: ${{ inputs.publint-status }}
        run: npx publint ${{ inputs.publint-input }}

      - name: Check package.json sort
        if: ${{ inputs.packagejson-status }}
        run: npx --yes sort-package-json --check
