name: QA

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        default: 16

      # eslint
      eslint-status:
        type: boolean
        default: true
      eslint-config:
        type: string
        default: config/.eslintrc.js
      eslint-input:
        type: string
        default: '.'

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "${{ inputs.eslint-status }}"
    steps:
      - uses: actions/checkout@v3

      - uses: yoriiis/eslint-action@main
