name: QA

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        default: 16

      # markdown
      markdown-status:
        type: boolean
        default: true
      markdown-config:
        type: string
        default: .markdownlint-cli2.cjs
      markdown-input:
        type: string
        default: '**/*.md'

      # stylelint
      stylelint-status:
        type: boolean
        default: true
      stylelint-config:
        type: string
        default: config/stylelint.config.js
      stylelint-input:
        type: string
        default: 'src/**/*.css'

      # eslint
      eslint-status:
        type: boolean
        default: true
      eslint-config:
        type: string
        default: config/.eslintrc.js
      eslint-input:
        type: string
        default: '.'

jobs:
  markdown:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "${{ inputs.markdown-status }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: .github/workflows/qa.yml
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: |
          npm install \
            markdownlint-cli2@0.8.1 \
            --global

      - name: Lint
        run: npx markdownlint-cli2 --config "${{ inputs.markdown-config }}" ${{ inputs.markdown-input }}

  stylelint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "${{ inputs.stylelint-status }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: .github/workflows/qa.yml
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: |
          npm install \
            stylelint@15.9.0 \
            stylelint-config-standard@33.0.0 \
            stylelint-prettier@3.0.0 \
            --global

      - name: Lint
        run: npx stylelint ${{ inputs.stylelint-input }} --config ${{ inputs.stylelint-config }}

  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "${{ inputs.eslint-status }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: .github/workflows/qa.yml
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: |
          npm install \
            @typescript-eslint/eslint-plugin@5.60.1 \
            @typescript-eslint/parser@5.60.1 \
            eslint@8.39.0 \
            eslint-config-prettier@8.8.0 \
            eslint-config-standard@17.0.0 \
            eslint-config-standard-with-typescript@36.0.0 \
            eslint-plugin-import@2.27.5 \
            eslint-plugin-n@15.7.0 \
            eslint-plugin-node@11.1.0 \
            eslint-plugin-prettier@4.2.1 \
            eslint-plugin-promise@6.1.1 \
            typescript@5.0.4 \
            --global

      - name: Lint
        run: npx eslint ${{ inputs.eslint-input }} --config ${{ inputs.eslint-config }}
