name: Deploy Vercel Functions

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        default: 16
      command-build:
        type: string
        default: npm run build
      working-directory:
        type: string
        default: ./functions
    secrets:
      VERCEL_ACCESS_TOKEN:
        required: true

jobs:
  deploy:
    environment: vercel-functions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./package-lock.json
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}

      - name: Build
        run: ${{ inputs.command-build }}
        working-directory: ${{ inputs.working-directory }}

      - name: Deploy Vercel Functions
        run: |
          npx vercel --prod --token ${{ secrets.VERCEL_ACCESS_TOKEN }}
        working-directory: ${{ inputs.working-directory }}
